### ISSUE TITLE
export presentational component separately

### ISSUE THREAD

**Issue by moodysalem** [rongierlach/react-web3-network-status#8]
i don't need the automatic querying, i just want to render the network status because react-web3 provides it already

**Comment by youfoundron** [comment]
I'll still need a way to deliver that state to the component. What would you prefer as an API?

Passing network id as a prop, will be on you to update this prop:
```javascript
const MyApp = ({networkId}) => (
  <div>
    <NetworkStatus networkId={networkId} />
  </div>
)
```

Passing web3 instance as a prop, polling the provided instance:
```javascript
const MyApp = ({web3}) => (
  <div>
    <NetworkStatus web3={web3} />
  </div>
)
```

Open to an alternative approach.

**Comment by moodysalem** [comment]
i prefer the first one, with just the `networkId`, because that's the minimum required information to render. also it'd be nice if the component didn't use `#id` styles because the user might want to render two of them

**Comment by moodysalem** [comment]
i guess in the minimal api you also want to add `account` so you can still link out to etherscan

**Comment by youfoundron** [comment]
You're right, `id` alone does not provide enough information for "no unlocked accounts" messaging.
Do you envision the presentational variant of the component handling this sort of messaging?

**Comment by moodysalem** [comment]
the two could be separate, e.g. `NoAccounts` and `NetworkStatus`

the `account` prop for `NetworkStatus` would be optional for linking to etherscan. Not sure how you handle multiple accounts currently

**Comment by youfoundron** [comment]
Initial value comes from the `web3.eth.defaultAccount` endpoint.

Since MetaMask only exposes one unlocked account at a time, the unlocked account is only ever the first item in the accounts list.

As accounts are polled, the first account in the list is being compared against the defaultAccount: https://github.com/rongierlach/react-web3-network-status/blob/master/src/state/sagas/defaultAccountSaga.js

I could see an application author wanting to link out to say, a contract address on etherscan, rather than the user's wallet, so `account` or maybe `address` prop makes sense.

**Comment by moodysalem** [comment]
I think `address` makes sense

**Comment by youfoundron** [comment]
Will implement the following tomorrow: 

```javascript
import { Stateless as NetworkStatus } from 'react-web3-network-status'

const MyApp = ({currNetworkId, myAddress}) => (
  <div>
    <NetworkStatus
      networkId={currNetworkId} // null or int
      address={myAddress} // string, optional
    />
  </div>
)
```

**Comment by moodysalem** [comment]
this component is still triggering tons of web3 calls.. it looks like it's sending them non-stop in fact. just importing the code is enough to trigger it

**Comment by moodysalem** [comment]
thanks for your quick responses by the way

**Comment by youfoundron** [comment]
@moodysalem np! v1.0.0 now. See updated docs n give it a go...

**Comment by youfoundron** [comment]
@moodysalem just curious, did the update meet your use-case?

**Comment by moodysalem** [comment]
it did! i wasn't able to get the address prop to work (but i didn't try very hard.) but my problem in this ticket is solved, and i don't think i saw any new web3 calls. thanks 👍

**Comment by youfoundron** [comment]
Nice! Good to know, let me know if the address bug is the component's fault.
